/**
 * Bot state machine states
 */
export const STATES = {
  IDLE: 'IDLE',
  FEATURE_SELECTION: 'FEATURE_SELECTION',
  EXCHANGE_SELECTION: 'EXCHANGE_SELECTION',
  SCAN_TYPE_SELECTION: 'SCAN_TYPE_SELECTION',
  FILTER_INPUT: 'FILTER_INPUT',
  TIME_RANGE_SELECTION: 'TIME_RANGE_SELECTION',
  CUSTOM_TIME_INPUT: 'CUSTOM_TIME_INPUT',
  FILTER_CONFIRMATION: 'FILTER_CONFIRMATION',
  SCANNING: 'SCANNING',
  RESULTS: 'RESULTS',

  PC_MENU: 'PC_MENU',
  PC_FUNC1_INPUT: 'PC_FUNC1_INPUT',
  PC_FUNC2_INPUT: 'PC_FUNC2_INPUT',
  PC_FUNC3_DATE_CUSTOM: 'PC_FUNC3_DATE_CUSTOM',
  PC_FUNC3_TIME_INPUT: 'PC_FUNC3_TIME_INPUT',
  PC_SCANNING: 'PC_SCANNING',
  PC_RESULTS: 'PC_RESULTS'
};

export default STATES;
