/**
 * Bot state machine states
 */
export const STATES = {
  IDLE: 'IDLE',
  FEATURE_SELECTION: 'FEATURE_SELECTION',
  EXCHANGE_SELECTION: 'EXCHANGE_SELECTION',
  SCAN_TYPE_SELECTION: 'SCAN_TYPE_SELECTION',
  FILTER_INPUT: 'FILTER_INPUT',
  TIME_RANGE_SELECTION: 'TIME_RANGE_SELECTION',
  CUSTOM_TIME_INPUT: 'CUSTOM_TIME_INPUT',
  FILTER_CONFIRMATION: 'FILTER_CONFIRMATION',
  SCANNING: 'SCANNING',
  RESULTS: 'RESULTS'
};

export default STATES;
